medical_holding/main/urls.py
from main.views import http404_page
from django.urls import path
from . import views


urlpatterns=[
    path('', views.Home.as_view(), name='home'),
    path('login/', views.MyLoginView.as_view(), name='log_in'),
    path('signup/', views.SignupView.as_view(), name='sign_up'),
    path('logout/', views.logout_page, name='log_out'),

    path('profile/user/<slug:username>/', views.ProfileUserView.as_view(), name='profile_user'),
    path('profile/user/<slug:username>/change/', views.ChangeProfileUserView.as_view(), name='change_profile_user'),
    path('ban/user/<slug:username>/', views.ban_user, name='ban_user'),
    path('unban/user/<slug:username>/', views.unban_user, name='unban_user'),

    path('organization/', views.OrganizationRouter.as_view(), name='router_organization'),
    path('organization/new/', views.RegisterOrganizationView.as_view(), name='new_organization'),
    path('profile/organization/<int:pk>/', views.OrganizationProfileView.as_view(), name='profile_organization'),
    path('profile/organization/<int:pk>/change/',
       views.ChangeProfileOrganizationView.as_view(), name='profile_organization_change'),

    path('profile/organization/<int:pk>/branch/',
         views.OrganizationBranchListView.as_view(), name='organization_branch_list'),
    path('profile/organization/<int:pk>/branch/new/',
         views.CreateBranchOrganizationView.as_view(), name='organization_branch_new'),
    path('profile/organization/<int:pk>/branch/<int:pk_branch>/change/',
         views.UpdateBranchOrganizationView.as_view(), name='organization_branch_change'),
    path('profile/organization/<int:pk>/branch/<int:pk_branch>/delete/',
         views.delete_organization_branch, name='organization_branch_delete'),

    path('profile/organization/<int:pk>/employee/',
         views.OrganizationEmployeeListView.as_view(), name='organization_employee_list'),
    path('profile/organization/<int:pk>/employee/new/',
         views.CreateEmployeeOrganizationView.as_view(), name='organization_employee_new'),
    path('profile/organization/<int:pk>/employee/<int:pk_employee>/change/',
         views.UpdateEmployeeOrganizationView.as_view(), name='organization_employee_change'),
    path('profile/organization/<int:pk>/employee/<int:pk_employee>/delete/',
         views.delete_organization_employee, name='organization_employee_delete'),

    path('services/', views.ServicesListView.as_view(), name='services_list'),
    path('services/new/', views.CreateServicesView.as_view(), name='services_new'),
    path('services/<int:pk>/', views.ServicesView.as_view(), name='services_view'),
    path('services/<int:pk>/change/',
         views.UpdateServicesView.as_view(), name='services_change'),
    path('services/<int:pk>/delete/',
         views.delete_organization_service, name='service_delete'),
    path('services/<int:pk>/grage/<int:pk_grade>/delete/', views.delete_grade_service , name='delete_rating'),
    path('services/organization/',
       views.OrganizationAppointmentListView.as_view(), name='appointment_organization'),

    path('services/comment/<int:pk>/delete/', views.delete_comment_service, name='delete_comment'),
    path('services/comment/<int:pk>/change/', views.ChangeCommentServicesView.as_view(), name='change_comment'),
]

handler404 = http404_page

medical_holding/medical_holding/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medical_holding/main/models.py
from django.core.validators import (RegexValidator, FileExtensionValidator,
                                    MinValueValidator, MaxValueValidator, MinLengthValidator)
from main.validators import validate_file_size, validate_service_appointment_time
from medical_holding.settings import AUTH_USER_MODEL
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager
from django.db.models import Q
from django.db import models


def validate_file_size_2mb(value):
    validate_file_size(value, 2)

def validate_file_size_4mb(value):
    validate_file_size(value, 4)


class Gender(models.TextChoices):
    MALE = 'M', 'Мужской'
    FEMALE = 'W', 'Женский'
    NONE = 'N', 'Не указан'


class User(AbstractUser):
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    avatar = models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d/', validators=[
        validate_file_size_2mb,
        FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']),
    ], default='default/avatar.jpg',
                               verbose_name='Аватар')
    background = models.ImageField(blank=True, upload_to='backgrounds/%Y/%m/%d/', validators=[
        validate_file_size_4mb,
        FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']),
    ], default='default/background.jpg',
                                   verbose_name='Фон профиля')
    about = models.TextField(max_length=1024, blank=True, default='', verbose_name='О себе')

    first_name = models.CharField(max_length=256,  blank=True, default='', verbose_name='Имя')
    last_name = models.CharField(max_length=256, blank=True, default='', verbose_name='Фамилия')
    gender = models.CharField(max_length=2, blank=True, choices=Gender.choices, default=Gender.NONE,
                              verbose_name='Пол')
    birthday = models.DateField(blank=True, null=True, verbose_name='День рождения')
    phone = models.CharField(blank=True, default='', validators=[
        RegexValidator(r'^\d{6,16}$', 'Номер телефона число от 6 до 16 цифр.')
    ], max_length=16, verbose_name='Номер телефона')

    email = models.EmailField(verbose_name='Почта')

    last_seen = models.DateTimeField(auto_now=True)
    is_online = models.BooleanField(default=False)
    banned = models.BooleanField(default=False, verbose_name='Заблокирован')

    objects = UserManager()


class Organization(models.Model):
    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'

    owner = models.OneToOneField(AUTH_USER_MODEL,
                                 related_name='owner_organization_fk',
                                 on_delete=models.PROTECT, verbose_name='Владелец организации')
    name = models.CharField(max_length=512, unique=True, validators=[
        MinLengthValidator(3),
    ], verbose_name='Название')
    logo = models.ImageField(upload_to='avatars/%Y/%m/%d/', validators=[
        validate_file_size_2mb,
        FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])
    ], default='default/avatar_organization.jpg',
                               verbose_name='Логотип')
    about = models.CharField(max_length=1024, default='', blank=True, verbose_name='Об организации')
    site = models.URLField(max_length=1024, default='', blank=True, verbose_name='Сайт')
    inn = models.CharField(max_length=12, unique=True,
                           validators=[
                               RegexValidator(r'^\d{10,12}$', 'ИНН должен содержать от 10 до 12 цифр.')
                           ], verbose_name='ИНН')

    objects = models.Manager()


class BranchOrganization(models.Model):
    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(house__gt=0),
                name='house_not_zero_CK',
            ),
        ]
        verbose_name = 'Филиал'
        verbose_name_plural = 'Филиалы'

    organization = models.ForeignKey(Organization,
                                     related_name='organization_branch_fk',
                                     on_delete=models.PROTECT, verbose_name='Филиал организации')
    street = models.CharField(max_length=512, validators=[
        MinLengthValidator(8),
    ], verbose_name='Улица')
    house = models.PositiveSmallIntegerField(validators=[
        MinValueValidator(1)
    ], verbose_name='Дом')
    phone = models.CharField(blank=True, default='', validators=[
        RegexValidator(r'^\d{6,16}$', 'Номер телефона число от 6 до 16 цифр.')
    ], max_length=16, verbose_name='Номер телефона')
    deleted = models.BooleanField(default=False, verbose_name='Удален')

    class NonDeletedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(deleted=False)

    objects = models.Manager()
    non_deleted = NonDeletedManager()

    def __str__(self):
        return f'Ул. {self.street} дом {self.house}'


class EmployeeOrganization(models.Model):
    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', default='default/employee.jpg', validators=[
        validate_file_size_2mb,
        FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']),
    ], verbose_name='Аватар')
    number_in_med_registry = models.CharField(max_length=128, unique=True, validators=[
        MinLengthValidator(1)
    ], verbose_name='Номер в медецинском реестре')
    organization = models.ForeignKey(Organization, related_name='organization_employee_fk',
                                     on_delete=models.PROTECT, verbose_name='Сотрудник организации')
    experience_month = models.PositiveSmallIntegerField(default=0, verbose_name='Опыт в месяцах')
    first_name = models.CharField(max_length=256, verbose_name='Имя')
    last_name = models.CharField(max_length=256, verbose_name='Фамилия')
    middle_name = models.CharField(max_length=256, verbose_name='Отчество')
    qualification = models.CharField(max_length=512, verbose_name='Квалификация')
    gender = models.CharField(max_length=2, choices=Gender.choices, default=Gender.NONE, verbose_name='Пол')
    deleted = models.BooleanField(default=False, verbose_name='Удален')

    class NonDeletedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(deleted=False)

    objects = models.Manager()
    non_deleted = NonDeletedManager()

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.middle_name} | {self.number_in_med_registry}'


class ServiceOrganization(models.Model):
    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(price__gte=0),
                name='price_CK',
            ),
        ]
        ordering = ['-date_created']
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

    branch = models.ForeignKey(BranchOrganization,
                               related_name='branch_organization_fk',
                               on_delete=models.PROTECT, verbose_name='Где будет проходить')
    name_service = models.CharField(max_length=512, validators=[
        MinLengthValidator(8)
    ], verbose_name='Название услуги')
    date_created = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    appointment_start_time = models.TimeField(verbose_name='Время начала приемов')
    appointment_end_time = models.TimeField(verbose_name='Время конца приемов')
    appointment_interval = models.PositiveSmallIntegerField(validators=[
            MinValueValidator(5, message='Минимальный интервал 5 минут')
        ],verbose_name='Интервал записей')
    amount_days_for_registration = models.PositiveSmallIntegerField(validators=[
            MinValueValidator(1, message='Минимум дней на оформление вперед это 1 день'),
            MaxValueValidator(14, message='Максимум на перед можно оформить только на 2 недели вперед')
        ], verbose_name='На сколько вперед дней можно оформить')
    employee = models.ManyToManyField(EmployeeOrganization, related_name='employee_organization_fk',
                                      verbose_name='Сотрудники, которые могут выполнять услугу')
    additional_information = models.CharField(max_length=1024, blank=True, verbose_name='Дополнительная информация')
    deleted = models.BooleanField(default=False, verbose_name='Удален')

    def clean(self):
        super().clean()
        validate_service_appointment_time(self.appointment_start_time, self.appointment_end_time, self.appointment_interval)

    class NonDeletedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(Q(deleted=False) &
                                                 Q(branch__organization__owner__banned=False))

    objects = models.Manager()
    non_deleted = NonDeletedManager()


class CommentAboutService(models.Model):
    class Meta:
        ordering = ['-date_created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_change = models.BooleanField(default=False, verbose_name='Изменен')
    wrote = models.ForeignKey(AUTH_USER_MODEL, related_name='wrote_comment_fk',
                              on_delete=models.PROTECT, verbose_name='Кто написал')
    text = models.CharField(max_length=1024, validators=[
        MinLengthValidator(1)
    ], verbose_name='Текст комментария')
    service = models.ForeignKey(ServiceOrganization, related_name='service_comment_fk',
                                on_delete=models.PROTECT, verbose_name='Комментарий к услуге')
    deleted = models.BooleanField(default=False, verbose_name='Удален')

    class NonDeletedManager(models.Manager):

medical_holding/main/templates/main/appointment_organization_list.html
{% extends "main/base.html" %}
{% load static %}


{% block title %}{{title}}{% endblock %}

{% block styles %}
<link type="text/css" rel="stylesheet" href="{% static 'main/css/appointment_list.css' %}"/>
{% endblock %}
{% block scripts %}{% endblock %}

{% block content %}
<div class="appointment-list">
    <h1>Список записей приёма</h1>

    <div class="appointment-items">
        {% for appointment in appointment_organization_list %}
        <div class="appointment-item">
            <p>
                <strong>Пациент:</strong> <a href="{% url 'profile_user' appointment.who_purchased.username %}">{{ appointment.who_purchased.username }}</a><br>
                <strong>Услуга:</strong> <a href="{% url 'services_view' appointment.service_now.id %}">{{ appointment.service_now.name_service }}</a><br>
                <strong>Специалист:</strong> {{ appointment.last_name_specialist }} {{ appointment.first_name_specialist }} {{ appointment.middle_name_specialist }}<br>
                <strong>Название услуги:</strong> {{ appointment.name_service }}<br>
                <strong>Дата и время приёма:</strong> {{ appointment.date_time_appointment }}<br>
                <strong>Цена:</strong> {{ appointment.price_appointment }}<br>
                <strong>Адрес филиала:</strong> {{ appointment.street_branch }}, {{ appointment.house_branch }}<br>
                <strong>Квалификация специалиста:</strong> {{ appointment.qualification_specialist }}<br>
            </p>
        </div>
        {% endfor %}
    </div>
    <br>
    {% include 'includes/pagination.html' %}
</div>
{% endblock %}

medical_holding/main/templates/main/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link type="text/css" rel="stylesheet" href="{% static 'main/css/main.css' %}"/>
    {% block styles %}{% endblock %}
    {% block scripts %}{% endblock %}
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                {% include 'includes/notification.html' with message=message message_type='error' display_time=5 %}
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                {% include 'includes/notification.html' with message=message message_type='warning' display_time=5 %}
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                {% include 'includes/notification.html' with message=message message_type='info' display_time=5 %}
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                {% include 'includes/notification.html' with message=message message_type='success' display_time=5 %}
            {% endif %}
        {% endfor %}
    {% endif %}
    <header>
        <div class="header-container">
            <div class="logo">
                <img src="{% static 'main/img/empty_logo.jpg' %}" alt="Logo" />
            </div>
            <nav class="nav-links">
                <a href="{% url 'home' %}" class="button">Главная</a>
                <a href="{% url 'services_list' %}" class="button">Услуги</a>
                <a href="{% url 'router_organization' %}" class="button">Организациям</a>
            </nav>
            <div class="auth-links">
                {% if user.is_authenticated %}
                    <div class="profile">
                        <a class="a-profile" href="{% url 'profile_user' user.username %}">
                            <img class="avatar" src="/media/{{ user.avatar }}" alt="Аватар" />
                            <p>Профиль</p>
                        </a>
                    </div>
                    <a class="button" href="{% url 'log_out' %}">Выйти</a>
                {% else %}
                    <a href="{% url 'sign_up' %}" class="button">Регистрация</a>
                    <a href="{% url 'log_in' %}" class="button">Вход</a>
                {% endif %}
            </div>
        </div>
    </header>
    <div id="wrapper">
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>
    <footer>
        <div class="footer-content">
            <p>©«Медицинский холдинг» 2025</p>
        </div>
    </footer>
</body>
</html>

medical_holding/main/templates/main/change_comment_service.html
{% extends "main/base.html" %}
{% load static %}


{% block title %}{{title}}{% endblock %}

{% block styles %}
<link type="text/css" rel="stylesheet" href="{% static 'main/css/form.css' %}"/>
{% endblock %}
{% block scripts %}{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="form-title">{{ title_form }}</h2>
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_text">Комментарий</label>
            <textarea name="text" id="id_text" class="form-control"
                      style="width: 100%; height: 150px; resize: none;" rows="5"
            >{{ form.text.value|default:"" }}</textarea>
            {{ form.text.errors }}
        </div>
        <button type="submit" class="form-button">Сохранить</button>
    </form>
</div>

{% endblock %}

medical_holding/main/templates/main/change_organization_profile.html
{% extends "main/base.html" %}
{% load static %}


{% block title %}{{title}}{% endblock %}

{% block styles %}
<link type="text/css" rel="stylesheet" href="{% static 'main/css/form.css' %}"/>
{% endblock %}
{% block scripts %}{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="form-title">{{ title_form }}</h2>
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_logo">Логотип</label>
            <input type="file" name="logo" id="id_logo" class="form-control">
            {{ form.logo.errors }}
        </div>

        <div class="form-group">
            <label for="id_name">Название</label>
            <input type="text" name="name" id="id_name" value="{{ form.name.value }}" class="form-control">
            {{ form.name.errors }}
        </div>

        <div class="form-group">
            <label for="id_about">О организации</label>
            <textarea name="about" id="id_about" class="form-control"
                      style="width: 100%; height: 150px; resize: none;" rows="5"
            >{{ form.about.value }}</textarea>
            {{ form.about.errors }}
        </div>

        <div class="form-group">
            <label for="id_site">Сайт</label>
            <input type="url" name="site" id="id_site" value="{{ form.site.value }}" class="form-control">
            {{ form.site.errors }}
        </div>

        <div class="form-group">
            <label for="id_inn">ИНН</label>
            <input type="text" name="inn" id="id_inn" value="{{ form.inn.value }}" class="form-control">
            {{ form.inn.errors }}
        </div>

        <button type="submit" class="form-button">Сохранить</button>
    </form>
</div>
{% endblock %}

medical_holding/main/templates/main/change_profile_user.html
{% extends "main/base.html" %}
{% load static %}


{% block title %}{{title}}{% endblock %}

{% block styles %}
<link type="text/css" rel="stylesheet" href="{% static 'main/css/form.css' %}"/>
{% endblock %}
{% block scripts %}{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="form-title">Изменить профиль</h2>
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_avatar">Аватар</label>
            <input type="file" name="avatar" id="id_avatar" class="form-control">
            {{ form.avatar.errors }}
        </div>

        <div class="form-group">
            <label for="id_background">Фон профиля</label>
            <input type="file" name="background" id="id_background" class="form-control">
            {{ form.background.errors }}
        </div>

        <div class="form-group">
            <label for="id_about">О себе</label>
            <textarea name="about" id="id_about" class="form-control"
                      style="width: 100%; height: 150px; resize: none;" rows="5"
            >{{ form.about.value }}</textarea>
            {{ form.about.errors }}
        </div>

        <div class="form-group">
            <label for="id_first_name">Имя</label>
            <input type="text" name="first_name" id="id_first_name" value="{{ form.first_name.value }}" class="form-control">
            {{ form.first_name.errors }}
        </div>

        <div class="form-group">
            <label for="id_last_name">Фамилия</label>
            <input type="text" name="last_name" id="id_last_name" value="{{ form.last_name.value }}" class="form-control">
            {{ form.last_name.errors }}
        </div>

        <div class="form-group">
            <label for="id_gender">Пол</label>
            <select name="gender" id="id_gender" class="form-control">
                {% for choice in form.gender.field.choices %}
                    {% if choice.0 != '' %}
                        <option value="{{ choice.0 }}" {% if choice.0 == form.gender.value %}selected{% endif %}>{{ choice.1 }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            {{ form.gender.errors }}
        </div>

        <div class="form-group">
            <label for="id_birthday">День рождения</label>
            <input type="date" name="birthday" id="id_birthday" value="{{ form.birthday.value }}" class="form-control">
            {{ form.birthday.errors }}
        </div>

        <div class="form-group">
            <label for="id_phone">Номер телефона</label>
            <input type="text" name="phone" id="id_phone" value="{{ form.phone.value }}" class="form-control">
            {{ form.phone.errors }}
        </div>

        <button type="submit" class="form-button">Изменить профиль</button>
    </form>
</div>
{% endblock %}

medical_holding/main/templates/main/form_branch_organization.html
{% extends "main/base.html" %}
{% load static %}


{% block title %}{{title}}{% endblock %}

{% block styles %}
<link type="text/css" rel="stylesheet" href="{% static 'main/css/form.css' %}"/>
{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="form-title">{{ title_form }}</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label>Улица</label>
            {{ form.street }}
            {{ form.street.errors }}
        </div>

        <div class="form-group">
            <label>Дом</label>
            {{ form.house }}
            {{ form.house.errors }}
        </div>

        <div class="form-group">
            <label>Телефон</label>
            {{ form.phone }}
            {{ form.phone.errors }}
        </div>

        <button type="submit" class="form-button">Сохранить</button>
    </form>
</div>
{% endblock %}

medical_holding/main/templates/main/form_employee_organization.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block styles %}
<link type="text/css" rel="stylesheet" href="{% static 'main/css/form.css' %}"/>
{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="form-title">{{ title_form }}</h2>
    <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label>Фото</label>
            {{ form.photo }}
            {{ form.photo.errors }}
        </div>

        <div class="form-group">
            <label>Стаж (в месяцах)</label>
            {{ form.experience_month }}
            {{ form.experience_month.errors }}
        </div>

        <div class="form-group">
            <label>Имя</label>
            {{ form.first_name }}
            {{ form.first_name.errors }}
        </div>

        <div class="form-group">
            <label>Фамилия</label>
            {{ form.last_name }}
            {{ form.last_name.errors }}
        </div>

        <div class="form-group">
            <label>Отчество</label>
            {{ form.middle_name }}
            {{ form.middle_name.errors }}
        </div>

        <div class="form-group">
            <label>Номер в медицинском регистре</label>
            {{ form.number_in_med_registry }}
            {{ form.number_in_med_registry.errors }}
        </div>

        <div class="form-group">
            <label>Квалификация</label>
            {{ form.qualification }}
            {{ form.qualification.errors }}
        </div>

        <div class="form-group">
            <label for="id_gender">Пол</label>
            <select name="gender" id="id_gender" class="form-control">
                {% for choice in form.gender.field.choices %}
                    {% if choice.0 != '' %}
                        <option value="{{ choice.0 }}" {% if choice.0 == form.gender.value %}selected{% endif %}>{{ choice.1 }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            {{ form.gender.errors }}
        </div>

        <button type="submit" class="form-button">Сохранить</button>
    </form>
</div>
{% endblock %}

medical_holding/main/templates/main/form_service_organization.html
{% extends "main/base.html" %}
{% load static %}


{% block title %}{{title}}{% endblock %}

{% block styles %}
<link type="text/css" rel="stylesheet" href="{% static 'main/css/form.css' %}"/>
{% endblock %}

{% block scripts %}{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="form-title">{{ title_form }}</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label>Название услуги</label>
            {{ form.name_service }}
            {{ form.name_service.errors }}
        </div>

        <div class="form-group">
            <label>Цена</label>
            {{ form.price }}
            {{ form.price.errors }}
        </div>

        <div class="form-group">
            <label>Где будет проходить</label>
            {{ form.branch }}
            {{ form.branch.errors }}
        </div>

        <div class="form-group">
            <label>Время начала приемов</label>
            {{ form.appointment_start_time }}
            {{ form.appointment_start_time.errors }}
        </div>

        <div class="form-group">
            <label>Время конца приемов</label>
            {{ form.appointment_end_time }}
            {{ form.appointment_end_time.errors }}
        </div>

        <div class="form-group">
            <label>Интервал записей</label>
            {{ form.appointment_interval }}
            {{ form.appointment_interval.errors }}
        </div>

        <div class="form-group">
            <label>На сколько вперед дней можно оформить</label>
            {{ form.amount_days_for_registration }}
            {{ form.amount_days_for_registration.errors }}
        </div>

        <div class="form-group">
            <label>Сотрудники, которые могут выполнять услугу</label>
            {% if form.employee.field.queryset.count > 0 %}
                {{ form.employee }}
                {{ form.employee.errors }}
            {% else %}
                <ul class="errorlist"><li>У вас нет сотрудников!</li></ul>
            {% endif %}
        </div>

        <div class="form-group">
            <label>Дополнительная информация</label>
            {{ form.additional_information }}
            {{ form.additional_information.errors }}
        </div>

        <button type="submit" class="form-button">Сохранить</button>
    </form>
</div>
{% endblock %}

medical_holding/main/templates/main/register_organization.html
{% extends "main/base.html" %}
{% load static %}


{% block title %}{{title}}{% endblock %}

{% block styles %}
<link type="text/css" rel="stylesheet" href="{% static 'main/css/form.css' %}"/>
{% endblock %}
{% block scripts %}{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="form-title">{{ title }}</h2>
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_name">Название организации</label>
            <input type="text" name="name" id="id_name" class="form-control">
            {{ form.name.errors }}
        </div>

        <div class="form-group">
            <label for="id_logo">Логотип</label>
            <input type="file" name="logo" id="id_logo" class="form-control">
            {{ form.logo.errors }}
        </div>

        <div class="form-group">
            <label for="id_about">О организации</label>
            <textarea name="about" id="id_about"
                      style="width: 100%; height: 150px; resize: none;" rows="5"
                      class="form-control"></textarea>
            {{ form.about.errors }}
        </div>

        <div class="form-group">
            <label for="id_site">Сайт (при наличии)</label>
            <input type="url" name="site" id="id_site" class="form-control">
            {{ form.site.errors }}
        </div>

        <div class="form-group">
            <label for="id_inn">ИНН</label>
            <input type="text" name="inn" id="id_inn" class="form-control">
            {{ form.inn.errors }}
        </div>

        <button type="submit" class="form-button">Зарегистрировать</button>
    </form>
</div>
{% endblock %}